// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anunibupzhmhhzygdeon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFudW5pYnVwemhtaGh6eWdkZW9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NDExNzcsImV4cCI6MjA3MDQxNzE3N30.x_d2J_VADOtaup2bBr-6nfC73FpLBrSlq7t8azPpz5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});